In [11]:
import sqlite3

conn = sqlite3.connect('business_cards.db')
c = conn.cursor()
c.execute('''CREATE TABLE IF NOT EXISTS business_cards
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
              company_name TEXT,
              card_holder_name TEXT,
              designation TEXT,
              mobile_number TEXT,
              email_address TEXT,
              website_url TEXT,
              area TEXT,
              city TEXT,
              state TEXT,
              pin_code TEXT,
              image BLOB)''')
def insert_data(company_name, card_holder_name, designation, mobile_number, email_address,
                website_url, area, city, state, pin_code, image):
    with conn:
        c.execute('''INSERT INTO business_cards
                     (company_name, card_holder_name, designation, mobile_number, email_address,
                      website_url, area, city, state, pin_code, image)
                     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''',
                  (company_name, card_holder_name, designation, mobile_number, email_address,
                   website_url, area, city, state, pin_code, image))
def display_data():
    with conn:
        c.execute('''SELECT * FROM business_cards''')
        rows = c.fetchall()
        for row in rows:
            st.write(f"Company name: {row[1]}")
            st.write(f"Card holder name: {row[2]}")
            st.write(f"Designation: {row[3]}")
            st.write(f"Mobile number: {row[4]}")
            st.write(f"Email address: {row[5]}")
            st.write(f"Website URL: {row[6]}")
            st.write(f"Address: {row[7]}")
            st.write(f"Area: {row[8]}")
            st.write(f"City: {row[9]}")
            st.write(f"State: {row[10]}")
            st.write(f"Pin code: {row[11]}")
            st.image(row[12])
def delete_data(card_id):
    with conn:
        c.execute('''DELETE FROM business_cards WHERE id=?''', (card_id,))

In [13]:
import streamlit as st
# import easyocr
# import cv2
import numpy as np
import io

def extract_text(image):
    reader = easyocr.Reader(['en'])
    result = reader.readtext(image)
    extracted_data = {}
    for r in result:
        if 'Company Name' in r[1]:
            extracted_data['Company Name'] = r[0]
        elif 'Name' in r[1]:
            extracted_data['Card Holder Name'] = r[0]
        elif 'Designation' in r[1]:
            extracted_data['Designation'] = r[0]
        elif 'Mobile' in r[1] or 'Phone' in r[1]:
            extracted_data['Mobile Number'] = r[0]
        elif 'Email' in r[1]:
            extracted_data['Email Address'] = r[0]
        elif 'Website' in r[1]:
            extracted_data['Website URL'] = r[0]
        elif 'Address' in r[1]:
            extracted_data['Address'] = r[0]
            address = extracted_data['Address'].split(',')
            if len(address) >= 3:
                extracted_data['Area'] = address[-3]
                extracted_data['City'] = address[-2]
                extracted_data['State'] = address[-1]
            if len(address) >= 4:
                extracted_data['Pin Code'] = address[-4]
    return extracted_data

def insert_data(company_name, card_holder_name, designation, mobile_number, email_address,
                website_url, area, city, state, pin_code, image):
    c.execute('''INSERT INTO business_cards
                 (company_name, card_holder_name, designation, mobile_number, email_address,
                  website_url, area, city, state, pin_code, image)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)''',
              (company_name, card_holder_name, designation, mobile_number, email_address,
               website_url, area, city, state, pin_code, image))
    conn.commit()

def display_data():
    c.execute('''SELECT * FROM business_cards''')
    rows = c.fetchall()
    for row in rows:
        st.write(f"Company name: {row[1]}")
        st.write(f"Card holder name: {row[2]}")
        st.write(f"Designation: {row[3]}")
        st.write(f"Mobile number: {row[4]}")
        st.write(f"Email address: {row[5]}")
        st.write(f"Website URL: {row[6]}")
        st.write(f"Address: {row[7]}")
        st.write(f"Area: {row[8]}")
        st.write(f"City: {row[9]}")
        st.write(f"State: {row[10]}")